CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth."user"(
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	github_id integer NOT NULL,
	username varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	avatar_url text NOT NULL
);