CREATE TABLE IF NOT EXISTS "system".file(
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id integer REFERENCES "system".workspace(id),
	original_name text NOT NULL,
	mime_type text NOT NULL,
	"size" integer NOT NULL,
	"path" text NOT NULL
);