CREATE SCHEMA IF NOT EXISTS "communication";

CREATE TABLE IF NOT EXISTS "communication"."channel" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id integer NOT NULL REFERENCES "system"."workspace"(id) ON DELETE CASCADE,
    created_by_id integer NOT NULL REFERENCES "auth"."user"(id),
    type varchar(16) NOT NULL CHECK (type IN ('DIRECT', 'GROUP')),
    name varchar(120),
    direct_key varchar(80),
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT communication_direct_channel_unique UNIQUE (direct_key),
    CONSTRAINT communication_channel_name_for_group CHECK (
        (type = 'GROUP' AND name IS NOT NULL) OR
        (type = 'DIRECT' AND direct_key IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS "communication"."channel_member" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id integer NOT NULL REFERENCES "communication"."channel"(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES "auth"."user"(id) ON DELETE CASCADE,
    last_read_at timestamp,
    muted_at timestamp,
    created_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT communication_channel_member_unique UNIQUE (channel_id, user_id)
);

CREATE TABLE IF NOT EXISTS "communication"."message" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id integer NOT NULL REFERENCES "communication"."channel"(id) ON DELETE CASCADE,
    sender_id integer NOT NULL REFERENCES "auth"."user"(id),
    content text,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT communication_message_has_body CHECK (content IS NOT NULL OR id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS "communication"."message_attachment" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id integer NOT NULL REFERENCES "communication"."message"(id) ON DELETE CASCADE,
    file_id integer NOT NULL REFERENCES "system"."file"(id) ON DELETE RESTRICT,
    CONSTRAINT communication_message_attachment_unique UNIQUE (message_id, file_id)
);

CREATE INDEX IF NOT EXISTS communication_channel_workspace_idx
    ON "communication"."channel"(workspace_id);
CREATE INDEX IF NOT EXISTS communication_member_user_idx
    ON "communication"."channel_member"(user_id);
CREATE INDEX IF NOT EXISTS communication_message_channel_created_idx
    ON "communication"."message"(channel_id, created_at);
