CREATE TABLE IF NOT EXISTS github.pull_request_reviewer (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pull_request_id integer NOT NULL REFERENCES github.pull_request(id) ON DELETE CASCADE,
  user_id integer REFERENCES auth."user"(id) ON DELETE SET NULL,
  github_user_id bigint,
  github_login varchar(255) NOT NULL,
  status varchar(40) NOT NULL DEFAULT 'pending',
  last_notified_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pull_request_reviewer_unique_login UNIQUE (pull_request_id, github_login)
);

CREATE INDEX IF NOT EXISTS pull_request_reviewer_pending_idx
ON github.pull_request_reviewer (status, pull_request_id);

CREATE INDEX IF NOT EXISTS pull_request_reviewer_user_idx
ON github.pull_request_reviewer (user_id);
