CREATE TABLE IF NOT EXISTS "system"."notification" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES "auth"."user"(id) ON DELETE CASCADE,
  workspace_id integer REFERENCES "system"."workspace"(id) ON DELETE CASCADE,
  type varchar(80) NOT NULL,
  title varchar(255) NOT NULL,
  message text NOT NULL,
  target_route varchar(255),
  target_url text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS notification_user_created_idx
  ON "system"."notification"(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS notification_user_unread_idx
  ON "system"."notification"(user_id, read_at)
  WHERE read_at IS NULL;

CREATE INDEX IF NOT EXISTS notification_workspace_idx
  ON "system"."notification"(workspace_id);
