CREATE TABLE IF NOT EXISTS "system"."workspace_member" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES "auth"."user"(id),
    workspace_id integer REFERENCES "system".workspace(id),
    role text CHECK (role IN ('ADMIN', 'MEMBER'))
);