CREATE TABLE IF NOT EXISTS github."label"(
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	repository_id integer NOT NULL REFERENCES github.repository(id),
	github_label_id bigint NOT NULL,
	name text NOT NULL,
	color text NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS github_label_repository_name_idx
ON github."label"(repository_id, name);
