CREATE TABLE IF NOT EXISTS "system"."expertise" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text,
    workspace_id integer NOT NULL REFERENCES "system".workspace(id)
);

CREATE TABLE IF NOT EXISTS "system"."user_expertise_assoc" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES "auth"."user"(id),
    expertise_id integer NOT NULL REFERENCES "system"."expertise"(id),
    CONSTRAINT user_expertise_assoc_unique_user_expertise UNIQUE (user_id, expertise_id)
);
