CREATE TABLE IF NOT EXISTS "system"."invitation"(
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(55) NOT NULL,
	workspace_id integer NOT NULL REFERENCES "system".workspace(id)
);