CREATE TABLE IF NOT EXISTS "system"."audit_event" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id integer REFERENCES "system"."workspace"(id) ON DELETE SET NULL,
  actor_user_id integer REFERENCES "auth"."user"(id) ON DELETE SET NULL,
  action varchar(120) NOT NULL,
  resource_type varchar(120) NOT NULL,
  resource_id varchar(120),
  source varchar(40) NOT NULL DEFAULT 'user',
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_event_workspace_created_idx
  ON "system"."audit_event"(workspace_id, created_at DESC);

CREATE INDEX IF NOT EXISTS audit_event_actor_created_idx
  ON "system"."audit_event"(actor_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS audit_event_resource_idx
  ON "system"."audit_event"(resource_type, resource_id);

CREATE INDEX IF NOT EXISTS audit_event_action_idx
  ON "system"."audit_event"(action);
