CREATE TABLE IF NOT EXISTS github."issue"(
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	repository_id integer NOT NULL REFERENCES github.repository(id),
	github_id bigint NOT NULL,
	title text NOT NULL,
	description text NOT NULL
);
