CREATE SCHEMA IF NOT EXISTS github;

CREATE TABLE IF NOT EXISTS github."repository"(
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	workspace_id integer NOT NULL REFERENCES "system".workspace(id),
	github_repo_id integer NOT NULL,
	name text NOT NULL,
	full_name text NOT NULL
);