CREATE TABLE IF NOT EXISTS "system"."news_feed_entry" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id integer NOT NULL REFERENCES "system"."workspace"(id),
    source_type varchar(64) NOT NULL,
    source_id integer NOT NULL,
    event_action varchar(32) NOT NULL,
    title text NOT NULL,
    summary text NOT NULL,
    ai_reason text,
    source_priority varchar(64),
    source_display_number varchar(64),
    repository_name varchar(255),
    happened_at timestamp NOT NULL
);

CREATE INDEX IF NOT EXISTS news_feed_entry_workspace_happened_at_idx
    ON "system"."news_feed_entry" (workspace_id, happened_at DESC);

CREATE TABLE IF NOT EXISTS "system"."news_feed_entry_expertise_assoc" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_feed_entry_id integer NOT NULL REFERENCES "system"."news_feed_entry"(id) ON DELETE CASCADE,
    expertise_id integer NOT NULL REFERENCES "system"."expertise"(id) ON DELETE CASCADE,
    CONSTRAINT news_feed_entry_expertise_assoc_unique_entry_expertise UNIQUE (news_feed_entry_id, expertise_id)
);

CREATE INDEX IF NOT EXISTS news_feed_entry_expertise_assoc_expertise_idx
    ON "system"."news_feed_entry_expertise_assoc" (expertise_id);
