CREATE SCHEMA IF NOT EXISTS "system";

CREATE TABLE IF NOT EXISTS "system".workspace(
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" varchar(255) NOT NULL,
	owner_id number NOT NULL REFERENCES auth."user"(id),
	github_installation_id text,
	avatar_url text,
	pr_review_reminder_cron varchar(55),
	issue_sync boolean NOT NULL DEFAULT TRUE,
	capacity_planning_sync boolean NOT NULL DEFAULT TRUE,
	pr_risk_prediction_sync boolean NOT NULL DEFAULT TRUE,
	reviewer_suggestion_sync boolean NOT NULL DEFAULT true
);
