CREATE SCHEMA IF NOT EXISTS "planning";

CREATE TABLE IF NOT EXISTS "planning"."capacity_plan" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id integer NOT NULL REFERENCES "system"."workspace"(id),
    "start" timestamp NOT NULL,
    "end" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "planning"."capacity_plan_entry" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacity_plan_id integer NOT NULL REFERENCES "planning"."capacity_plan"(id),
    user_id integer NOT NULL REFERENCES "auth"."user"(id),
    capacity_hours double precision NOT NULL,
    CONSTRAINT capacity_plan_entry_unique_plan_user UNIQUE (capacity_plan_id, user_id)
);

CREATE TABLE IF NOT EXISTS "planning"."issue_assignment" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id integer NOT NULL REFERENCES "github"."issue"(id),
    user_id integer NOT NULL REFERENCES "auth"."user"(id),
    capacity_plan_id integer NOT NULL REFERENCES "planning"."capacity_plan"(id),
    assigned_hours double precision NOT NULL,
    CONSTRAINT issue_assignment_unique_issue_user_plan UNIQUE (issue_id, user_id, capacity_plan_id)
);
