ALTER TABLE auth."user"
ALTER COLUMN github_id TYPE bigint;

ALTER TABLE github."issue"
ADD COLUMN IF NOT EXISTS github_issue_number integer;

CREATE TABLE IF NOT EXISTS github."pull_request"(
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	repository_id integer NOT NULL REFERENCES github.repository(id),
	github_pr_number integer NOT NULL,
	title text NOT NULL,
	description text NOT NULL,
	author_id integer REFERENCES auth."user"(id)
);
