name: Lint & Build

on:
  push:
    branches: [master]
    paths:
      - "api/**"
      - "client/**"
      - ".github/workflows/lint-and-build.yaml"
  pull_request:
    branches:
      - "*"
    paths:
      - "api/**"
      - "client/**"
      - ".github/workflows/lint-and-build.yaml"

permissions:
  contents: read

jobs:
  api-lint:
    name: API lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run API lint
        working-directory: api
        run: pnpm run lint

  api-build:
    name: API build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run API build
        working-directory: api
        run: pnpm run build

  client-lint:
    name: Client lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run client lint
        working-directory: client
        run: pnpm run lint

  client-build:
    name: Client build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run client build
        working-directory: client
        run: pnpm run build
